apiVersion: v1
kind: Namespace
metadata:
  name: cattle-system
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: rancher
  namespace: kube-system
spec:
  chart: https://%{KUBERNETES_API}%/static/charts/rancher-2.6.8.tgz
  targetNamespace: cattle-system
  valuesContent: |
    useBundledSystemChart: true
    hostname: "YOUR_RANCHER_HOSTNAME"
    replicas: 1
    ingress:
      tls:
        source: "rancher"
