name: Release
on: push
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # PREPARE BUILDX
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      # BUILD WITH BUILDX
      - run: mkdir -p output
      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: false
          cache-from: type=gha
          cache-to: type=gha
          outputs: type=local,dest=output
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            output/*

